server:
  port: 8090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: notification-microservice
          uri: lb://notification-microservice
          predicates:
            - Path=/notification/**
          filters:
            - EjemploCookie=MCSNOTIFICATION, usuario, basico

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
#      routes:
#        - id: portalModule

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka